version: '2'
services:
  etl-prod:
    container_name: etl-rest-server-prod
    image: ampathke/etl-services:v2.16.5.2
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - TZ=Africa/Nairobi
    dns:
      - 10.50.80.35
      - 8.8.8.8

    volumes:
      - /media/data/etl/conf:/opt/etl/conf
      - /media/data/etl/uploads:/opt/etl/uploads
      # deploy:
      #   mode: replicated
      #   replicas: 1
      #   placement:
      #     constraints:
      #      - node.hostname == upgrade1
    ports:
      - 9141:8002
