version: '2'
services:
  etl-prod:
    container_name: etl-rest-server-prod
    image: ampathke/etl-services:<tag>
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - TZ=Africa/Nairobi
    dns:
      - 10.50.80.35
      - 8.8.8.8

    volumes:
      - <source_directory>:/opt/etl/conf
      - <source_directory>:/opt/etl/uploads
      # deploy:
      #   mode: replicated
      #   replicas: 1
      #   placement:
      #     constraints:
      #      - node.hostname == upgrade1
    ports:
      - <server_port>:8002
