name: Deploy beta
on:
  push:
    branches: [master]
jobs:
  approve:
    runs-on: ubuntu-latest

    steps:
    -
      name: Approve
      run: echo For security reasons, all pull requests need to be approved first before running any automated CI.

  build_and_publish:
    name: Build Publish and Deploy Beta

    runs-on: ubuntu-latest

    needs: [approve]
    environment:
      name: Deploy Test Build

    steps:
      -
        name: Check Out Repo
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/etl-rest-server/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ampathke/etl-services:beta
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - 
        name: Spin up ETL nomad job
        uses: fjogeleit/http-request-action@master
        with:
          url: https://${{ secrets.AMPATH_CI_HOST }}/levant/deploy?branch=${{ steps.extract_branch.outputs.branch }}
          method: "GET"
          customHeaders: '{ "Accept": "application/json", "Content-Type": "application/json" }'
      - 
        name: Expose an external URL
        uses: fjogeleit/http-request-action@master
        with:
          url: https://${{ secrets.AMPATH_CI_HOST }}/etl?branch=${{ steps.extract_branch.outputs.branch }}
          method: "GET"
          customHeaders: '{ "Accept": "application/json", "Content-Type": "application/json" }'

